[package]
name = "hls_graph_ir"
version = "0.1.0"
authors = ["Izumi Asakura <i.asakura58@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "1.0"
itertools = "0.10.0"
log = "0.4"
env_logger = "0.8.2"
dot = "0.1.4"
indexmap = "1.6.1"